import {
  existsSync,
  readFileSync,
} from "node:fs";
import {
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { join } from "node:path";

import type {
  DouyinSessionCapturePhase,
  DouyinSessionState,
} from "../src/types/douyinSession.js";
import type { ManagedRuntimeBootstrapOptions } from "./managedRuntimeBootstrap.mjs";

export const REQUIRED_DOUYIN_SESSION_KEYS = [
  "msToken",
  "ttwid",
  "odin_tt",
  "passport_csrf_token",
] as const;

type RequiredDouyinSessionKey = (typeof REQUIRED_DOUYIN_SESSION_KEYS)[number];

type StoredDouyinSession = {
  capturedAtMs: number;
  cookies: Record<string, string>;
  cookieHeader: string;
  cookiesNetscape: string;
};

type DouyinSessionManagerOptions = {
  getUserDataDir(): string;
  buildManagedRuntimeBootstrapOptions(): ManagedRuntimeBootstrapOptions;
  managedDouyinDlRuntimePaths(
    options: ManagedRuntimeBootstrapOptions,
  ): { root: string; python: string };
  ensureManagedDouyinDlRuntimeReady(
    trigger: string,
    options: ManagedRuntimeBootstrapOptions,
  ): Promise<string>;
  ensureManagedDouyinDlBrowserSupportReady(
    trigger: string,
    options: ManagedRuntimeBootstrapOptions,
  ): Promise<void>;
  log?(message: string, details?: unknown): void;
  now?(): number;
};

type DouyinSessionManager = {
  getState(): Promise<DouyinSessionState>;
  startCapture(): Promise<DouyinSessionState>;
  confirmCapture(): Promise<DouyinSessionState>;
  cancelCapture(): Promise<DouyinSessionState>;
  clearSession(): Promise<DouyinSessionState>;
  shutdown(): Promise<void>;
  getDownloadCookies(): string | null;
};

const defaultNow = (): number => Date.now();

const normalizeCookieValue = (value: unknown): string | null => {
  if (typeof value !== "string") {
    return null;
  }
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
};

export const sanitizeDouyinCookieRecord = (
  value: unknown,
): Record<string, string> => {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }

  const entries = Object.entries(value as Record<string, unknown>)
    .map(([key, raw]) => [key.trim(), normalizeCookieValue(raw)] as const)
    .filter((entry): entry is readonly [string, string] => entry[0].length > 0 && entry[1] !== null);

  return Object.fromEntries(entries);
};

export const buildDouyinCookieHeader = (
  cookies: Record<string, string>,
): string => Object.entries(cookies)
  .map(([name, value]) => `${name}=${value}`)
  .join("; ");

export const buildDouyinNetscapeCookies = (
  cookies: Record<string, string>,
): string => {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# This file was generated by Ameow",
    "",
  ];

  for (const [name, value] of Object.entries(cookies)) {
    lines.push([
      ".douyin.com",
      "TRUE",
      "/",
      "TRUE",
      "0",
      name,
      value,
    ].join("\t"));
  }

  return `${lines.join("\n")}\n`;
};

const listMissingRequiredKeys = (
  cookies: Record<string, string>,
): RequiredDouyinSessionKey[] => REQUIRED_DOUYIN_SESSION_KEYS.filter((key) => !normalizeCookieValue(cookies[key]));

const getSessionFilePath = (userDataDir: string): string => join(userDataDir, "douyin-session.json");

const getCaptureOutputPath = (userDataDir: string): string => join(userDataDir, "douyin-session-capture.json");

const summarizeError = (error: unknown): string => (
  error instanceof Error && error.message ? error.message : String(error ?? "unknown error")
);

const deriveDouyinSessionState = ({
  session,
  sessionFilePath,
  capturePhase,
  captureStartedAtMs,
  capturePid,
  lastError,
}: {
  session: StoredDouyinSession | null;
  sessionFilePath: string;
  capturePhase: DouyinSessionCapturePhase;
  captureStartedAtMs: number | null;
  capturePid: number | null;
  lastError: string | null;
}): DouyinSessionState => {
  const cookies = session?.cookies ?? {};
  const missingRequiredKeys = listMissingRequiredKeys(cookies);
  const cookieCount = Object.keys(cookies).length;

  return {
    availability:
      cookieCount === 0
        ? "missing"
        : missingRequiredKeys.length > 0
          ? "partial"
          : "ready",
    updatedAtMs: session?.capturedAtMs ?? null,
    cookieCount,
    requiredKeys: [...REQUIRED_DOUYIN_SESSION_KEYS],
    missingRequiredKeys,
    lastError,
    sessionFilePath: existsSync(sessionFilePath) ? sessionFilePath : null,
    capturePhase,
    captureStartedAtMs,
    capturePid,
  };
};

const loadStoredDouyinSessionSync = (
  sessionFilePath: string,
): StoredDouyinSession | null => {
  if (!existsSync(sessionFilePath)) {
    return null;
  }

  try {
    const raw = readFileSync(sessionFilePath, "utf8");
    const parsed = JSON.parse(raw) as unknown;
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return null;
    }

    const record = parsed as Record<string, unknown>;
    const cookies = sanitizeDouyinCookieRecord(record.cookies);
    if (Object.keys(cookies).length === 0) {
      return null;
    }

    return {
      capturedAtMs: Number(record.capturedAtMs) || 0,
      cookies,
      cookieHeader: normalizeCookieValue(record.cookieHeader) ?? buildDouyinCookieHeader(cookies),
      cookiesNetscape: normalizeCookieValue(record.cookiesNetscape) ?? buildDouyinNetscapeCookies(cookies),
    };
  } catch {
    return null;
  }
};

export const createDouyinSessionManager = (
  options: DouyinSessionManagerOptions,
): DouyinSessionManager => {
  const now = options.now ?? defaultNow;
  const userDataDir = options.getUserDataDir();
  const sessionFilePath = getSessionFilePath(userDataDir);
  let sessionCache: StoredDouyinSession | null | undefined;
  let capturePhase: DouyinSessionCapturePhase = "idle";
  let captureStartedAtMs: number | null = null;
  let captureProcess: ChildProcessWithoutNullStreams | null = null;
  let captureOutputPath: string | null = null;
  let lastError: string | null = null;
  let captureCancelled = false;
  const stdoutTail: string[] = [];
  const stderrTail: string[] = [];

  const appendTailLine = (tail: string[], chunk: string): void => {
    const trimmed = chunk
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);
    for (const line of trimmed) {
      tail.push(line);
      if (tail.length > 12) {
        tail.shift();
      }
    }
  };

  const getBootstrapOptions = (): ManagedRuntimeBootstrapOptions => (
    options.buildManagedRuntimeBootstrapOptions()
  );

  const ensureSessionCacheLoaded = (): void => {
    if (sessionCache !== undefined) {
      return;
    }
    sessionCache = loadStoredDouyinSessionSync(sessionFilePath);
  };

  const currentState = (): DouyinSessionState => {
    ensureSessionCacheLoaded();
    return deriveDouyinSessionState({
      session: sessionCache ?? null,
      sessionFilePath,
      capturePhase,
      captureStartedAtMs,
      capturePid: captureProcess?.pid ?? null,
      lastError,
    });
  };

  const finalizeCaptureSuccess = async (outputPath: string): Promise<void> => {
    const raw = await readFile(outputPath, "utf8");
    const parsed = JSON.parse(raw) as unknown;
    const cookies = sanitizeDouyinCookieRecord(parsed);
    if (Object.keys(cookies).length === 0) {
      throw new Error("Douyin cookie capture finished without saving any cookies.");
    }

    const session: StoredDouyinSession = {
      capturedAtMs: now(),
      cookies,
      cookieHeader: buildDouyinCookieHeader(cookies),
      cookiesNetscape: buildDouyinNetscapeCookies(cookies),
    };

    await writeFile(sessionFilePath, `${JSON.stringify(session, null, 2)}\n`, "utf8");
    sessionCache = session;
    lastError = null;
  };

  const finalizeCaptureClose = async (exitCode: number | null): Promise<void> => {
    const outputPath = captureOutputPath;
    const didCancel = captureCancelled;
    capturePhase = "idle";
    captureStartedAtMs = null;
    captureProcess = null;
    captureOutputPath = null;
    captureCancelled = false;

    try {
      if (didCancel) {
        lastError = null;
        return;
      }

      if (exitCode === 0 && outputPath) {
        await finalizeCaptureSuccess(outputPath);
        return;
      }

      const diagnosticLine = stderrTail.at(-1) ?? stdoutTail.at(-1);
      lastError = diagnosticLine
        ?? (exitCode === null
          ? "Douyin session capture exited unexpectedly."
          : `Douyin session capture exited with code ${exitCode}.`);
    } finally {
      stdoutTail.length = 0;
      stderrTail.length = 0;
      if (outputPath) {
        await rm(outputPath, { force: true }).catch(() => {});
      }
    }
  };

  const startCapture = async (): Promise<DouyinSessionState> => {
    if (captureProcess) {
      return currentState();
    }

    lastError = null;
    capturePhase = "preparing";
    captureStartedAtMs = now();

    const bootstrapOptions = getBootstrapOptions();
    await options.ensureManagedDouyinDlRuntimeReady("douyin_session_capture", bootstrapOptions);
    await options.ensureManagedDouyinDlBrowserSupportReady("douyin_session_capture", bootstrapOptions);
    const runtimePaths = options.managedDouyinDlRuntimePaths(bootstrapOptions);
    const outputPath = getCaptureOutputPath(userDataDir);
    await rm(outputPath, { force: true }).catch(() => {});

    const env = {
      ...process.env,
      PLAYWRIGHT_BROWSERS_PATH: join(runtimePaths.root, "playwright-browsers"),
      PYTHONIOENCODING: "utf-8",
      PYTHONUTF8: "1",
    };

    const child = spawn(
      runtimePaths.python,
      [
        "-m",
        "tools.cookie_fetcher",
        "--output",
        outputPath,
      ],
      {
        cwd: runtimePaths.root,
        env,
        stdio: ["pipe", "pipe", "pipe"],
        windowsHide: true,
      },
    );

    captureProcess = child;
    captureOutputPath = outputPath;
    capturePhase = "awaiting_confirmation";
    child.stdout.on("data", (chunk) => {
      appendTailLine(stdoutTail, chunk.toString());
    });
    child.stderr.on("data", (chunk) => {
      appendTailLine(stderrTail, chunk.toString());
    });
    child.once("error", (error) => {
      lastError = summarizeError(error);
    });
    child.once("close", (code) => {
      void finalizeCaptureClose(code).catch((error) => {
        lastError = summarizeError(error);
      });
    });
    options.log?.("Started Douyin session capture", {
      pid: child.pid ?? null,
      outputPath,
    });

    return currentState();
  };

  return {
    async getState() {
      return currentState();
    },
    async startCapture() {
      try {
        return await startCapture();
      } catch (error) {
        capturePhase = "idle";
        captureStartedAtMs = null;
        captureProcess = null;
        captureOutputPath = null;
        lastError = summarizeError(error);
        return currentState();
      }
    },
    async confirmCapture() {
      if (!captureProcess || capturePhase !== "awaiting_confirmation") {
        return currentState();
      }
      captureProcess.stdin.write("\n");
      return currentState();
    },
    async cancelCapture() {
      if (!captureProcess) {
        return currentState();
      }
      captureCancelled = true;
      captureProcess.kill();
      return currentState();
    },
    async clearSession() {
      sessionCache = null;
      lastError = null;
      await rm(sessionFilePath, { force: true }).catch(() => {});
      return currentState();
    },
    async shutdown() {
      if (!captureProcess) {
        return;
      }
      captureCancelled = true;
      captureProcess.kill();
    },
    getDownloadCookies() {
      ensureSessionCacheLoaded();
      return normalizeCookieValue(sessionCache?.cookiesNetscape) ?? null;
    },
  };
};
