import { existsSync, readFileSync } from "node:fs";
import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type {
  SiteSessionCapturePhase,
  SiteSessionDiagnostics,
  SiteSessionState,
} from "../src/types/siteSession.js";
import {
  evaluateSiteSessionPolicy,
} from "./siteSessionPolicy.mjs";

type StoredSiteSession = {
  capturedAtMs: number;
  cookies: Record<string, string>;
  cookieHeader: string;
  cookiesNetscape: string;
};

export type SiteSessionDefinition = {
  id: string;
  displayName: string;
  loginUrl: string;
  cookieDomains: string[];
  requiredCookieKeys?: string[];
  loginCookieKeys?: string[];
};

type CaptureWindow = {
  id: number;
  close(): void;
};

type CreateCaptureWindowOptions = {
  site: SiteSessionDefinition;
  partition: string;
  onClosed(): void;
};

type SiteSessionManagerOptions = {
  site: SiteSessionDefinition;
  getUserDataDir(): string;
  createCaptureWindow(options: CreateCaptureWindowOptions): Promise<CaptureWindow>;
  readSupplementalCookies?(partition: string): Promise<Record<string, string>>;
  readCookies(partition: string): Promise<Array<{
    domain?: string;
    expirationDate?: number;
    httpOnly?: boolean;
    name?: string;
    path?: string;
    secure?: boolean;
    value?: string;
  }>>;
  destroyPartition?(partition: string): Promise<void>;
  log?(message: string, details?: unknown): void;
  now?(): number;
};

export type SiteSessionManager = {
  getState(): Promise<SiteSessionState>;
  getDiagnostics(): Promise<SiteSessionDiagnostics>;
  startCapture(): Promise<SiteSessionState>;
  confirmCapture(): Promise<SiteSessionState>;
  cancelCapture(): Promise<SiteSessionState>;
  refreshCredentials(): Promise<SiteSessionState>;
  clearSession(): Promise<SiteSessionState>;
  shutdown(): Promise<void>;
  getDownloadCookies(): string | null;
};

const defaultNow = (): number => Date.now();

const normalizeCookieValue = (value: unknown): string | null => {
  if (typeof value !== "string") {
    return null;
  }
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
};

const sanitizeCookieRecord = (
  value: unknown,
): Record<string, string> => {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }

  const entries = Object.entries(value as Record<string, unknown>)
    .map(([key, raw]) => [key.trim(), normalizeCookieValue(raw)] as const)
    .filter((entry): entry is readonly [string, string] => entry[0].length > 0 && entry[1] !== null);

  return Object.fromEntries(entries);
};

const buildCookieHeader = (
  cookies: Record<string, string>,
): string => Object.entries(cookies)
  .map(([name, value]) => `${name}=${value}`)
  .join("; ");

const mergeSupplementalCookies = (
  primaryCookies: Record<string, string>,
  supplementalCookies: Record<string, string>,
): Record<string, string> => {
  const merged = { ...primaryCookies };
  const supplemental = sanitizeCookieRecord(supplementalCookies);
  for (const [name, value] of Object.entries(supplemental)) {
    if (!normalizeCookieValue(merged[name])) {
      merged[name] = value;
    }
  }
  return merged;
};

const normalizeCookieDomain = (domain: string): string => domain.trim().replace(/^\./, "").toLowerCase();

const domainMatches = (cookieDomain: string, allowedDomain: string): boolean => {
  const normalizedCookieDomain = normalizeCookieDomain(cookieDomain);
  const normalizedAllowedDomain = normalizeCookieDomain(allowedDomain);
  return normalizedCookieDomain === normalizedAllowedDomain
    || normalizedCookieDomain.endsWith(`.${normalizedAllowedDomain}`);
};

const isCookieForSite = (
  domain: string | null,
  allowedDomains: string[],
): boolean => {
  const normalizedDomain = normalizeCookieValue(domain);
  if (!normalizedDomain) {
    return false;
  }
  return allowedDomains.some((allowedDomain) => domainMatches(normalizedDomain, allowedDomain));
};

const buildNetscapeCookies = (
  cookies: Array<{
    domain: string;
    expirationDate?: number;
    name: string;
    path?: string;
    secure?: boolean;
    value: string;
  }>,
): string => {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# This file was generated by Ameow",
    "",
  ];

  const sortedCookies = [...cookies].sort((left, right) => (
    `${left.domain}\t${left.name}`.localeCompare(`${right.domain}\t${right.name}`)
  ));

  for (const cookie of sortedCookies) {
    const domain = cookie.domain.startsWith(".") ? cookie.domain : `.${cookie.domain}`;
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const expires = Number.isFinite(cookie.expirationDate) && Number(cookie.expirationDate) > 0
      ? String(Math.floor(Number(cookie.expirationDate)))
      : "0";
    lines.push([
      domain,
      includeSubdomains,
      cookie.path?.trim() || "/",
      cookie.secure ? "TRUE" : "FALSE",
      expires,
      cookie.name,
      cookie.value,
    ].join("\t"));
  }

  return `${lines.join("\n")}\n`;
};

const getSessionFilePath = (userDataDir: string, siteId: string): string => (
  join(userDataDir, "site-sessions", `${siteId}.json`)
);

const getSessionTempFilePath = (sessionFilePath: string): string => (
  `${sessionFilePath}.tmp`
);

export const resolveSiteSessionProfilePartition = (siteId: string): string => (
  `persist:ameow-site-session-${siteId}`
);

const summarizeError = (error: unknown): string => (
  error instanceof Error && error.message ? error.message : String(error ?? "unknown error")
);

const loadStoredSiteSessionSync = (
  sessionFilePath: string,
): StoredSiteSession | null => {
  if (!existsSync(sessionFilePath)) {
    return null;
  }

  try {
    const raw = readFileSync(sessionFilePath, "utf8");
    const parsed = JSON.parse(raw) as unknown;
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return null;
    }

    const record = parsed as Record<string, unknown>;
    const cookies = sanitizeCookieRecord(record.cookies);
    const cookiesNetscape = normalizeCookieValue(record.cookiesNetscape);
    if (Object.keys(cookies).length === 0 || !cookiesNetscape) {
      return null;
    }

    return {
      capturedAtMs: Number(record.capturedAtMs) || 0,
      cookies,
      cookieHeader: normalizeCookieValue(record.cookieHeader) ?? buildCookieHeader(cookies),
      cookiesNetscape,
    };
  } catch {
    return null;
  }
};

export const createSiteSessionManager = (
  options: SiteSessionManagerOptions,
): SiteSessionManager => {
  const now = options.now ?? defaultNow;
  const userDataDir = options.getUserDataDir();
  const sessionFilePath = getSessionFilePath(userDataDir, options.site.id);
  const stableProfilePartition = resolveSiteSessionProfilePartition(options.site.id);
  const requiredCookieKeys = options.site.requiredCookieKeys ?? [];
  const loginCookieKeys = options.site.loginCookieKeys ?? [];
  let sessionCache: StoredSiteSession | null | undefined;
  let capturePhase: SiteSessionCapturePhase = "idle";
  let captureStartedAtMs: number | null = null;
  let captureWindow: CaptureWindow | null = null;
  let capturePartition: string | null = null;
  let lastError: string | null = null;

  const ensureSessionCacheLoaded = (): void => {
    if (sessionCache !== undefined) {
      return;
    }
    sessionCache = loadStoredSiteSessionSync(sessionFilePath);
  };

  const currentState = (): SiteSessionState => {
    ensureSessionCacheLoaded();
    const cookies = sessionCache?.cookies ?? {};
    const policy = evaluateSiteSessionPolicy({
      cookies,
      requiredKeys: requiredCookieKeys,
      loginKeys: loginCookieKeys,
    });
    const cookieCount = Object.keys(cookies).length;

    return {
      siteId: options.site.id,
      availability: policy.availability,
      updatedAtMs: sessionCache?.capturedAtMs ?? null,
      cookieCount,
      requiredKeys: [...requiredCookieKeys],
      missingRequiredKeys: policy.missingRequiredKeys,
      lastError,
      sessionFilePath: existsSync(sessionFilePath) ? sessionFilePath : null,
      capturePhase,
      captureStartedAtMs,
      capturePid: captureWindow?.id ?? null,
    };
  };

  const profileDiagnostics = async (): Promise<Pick<SiteSessionDiagnostics, "profileState" | "lastError">> => {
    try {
      const rawCookies = await options.readCookies(stableProfilePartition);
      const hasSiteProfileCookie = rawCookies.some((cookie) => (
        isCookieForSite(cookie.domain ?? null, options.site.cookieDomains)
        && Boolean(normalizeCookieValue(cookie.name))
        && normalizeCookieValue(cookie.value) !== null
      ));
      return {
        profileState: hasSiteProfileCookie ? "present" : "missing",
        lastError: null,
      };
    } catch (error) {
      return {
        profileState: "unknown",
        lastError: summarizeError(error),
      };
    }
  };

  const currentDiagnostics = async (): Promise<SiteSessionDiagnostics> => {
    const state = currentState();
    const profile = await profileDiagnostics();
    const policy = evaluateSiteSessionPolicy({
      cookies: sessionCache?.cookies ?? {},
      requiredKeys: requiredCookieKeys,
      loginKeys: loginCookieKeys,
    });

    return {
      siteId: options.site.id,
      profileState: profile.profileState,
      snapshotAvailability: state.availability,
      snapshotUpdatedAtMs: state.updatedAtMs,
      snapshotCookieCount: state.cookieCount,
      missingRequiredKeys: state.missingRequiredKeys,
      lastError: profile.lastError ?? state.lastError,
      policy,
    };
  };

  const closeCaptureWindow = (): void => {
    const window = captureWindow;
    captureWindow = null;
    capturePhase = "idle";
    captureStartedAtMs = null;
    if (window) {
      try {
        window.close();
      } catch {
        // Ignore close races when the user already closed the window.
      }
    }
  };

  const saveCredentialSnapshot = async (
    partition: string,
    options_: {
      includeSupplementalCookies: boolean;
    },
  ): Promise<StoredSiteSession> => {
    const rawCookies = await options.readCookies(partition);
    const siteCookies = rawCookies
      .map((cookie) => ({
        domain: normalizeCookieValue(cookie.domain),
        expirationDate: cookie.expirationDate,
        name: normalizeCookieValue(cookie.name),
        path: normalizeCookieValue(cookie.path) ?? "/",
        secure: cookie.secure === true,
        value: typeof cookie.value === "string" ? cookie.value : "",
      }))
      .filter((cookie) => Boolean(cookie.domain && cookie.name))
      .filter((cookie) => isCookieForSite(cookie.domain, options.site.cookieDomains))
      .map((cookie) => ({
        domain: cookie.domain as string,
        expirationDate: cookie.expirationDate,
        name: cookie.name as string,
        path: cookie.path,
        secure: cookie.secure,
        value: cookie.value,
      }));

    const primaryCookies = sanitizeCookieRecord(Object.fromEntries(
      siteCookies.map((cookie) => [cookie.name, cookie.value]),
    ));
    const supplementalCookies = options_.includeSupplementalCookies && options.readSupplementalCookies
      ? await options.readSupplementalCookies(partition)
      : {};
    const cookies = mergeSupplementalCookies(primaryCookies, supplementalCookies);
    if (Object.keys(cookies).length === 0) {
      throw new Error(`${options.site.displayName} cookie capture finished without saving any cookies.`);
    }

    const session: StoredSiteSession = {
      capturedAtMs: now(),
      cookies,
      cookieHeader: buildCookieHeader(cookies),
      cookiesNetscape: buildNetscapeCookies(siteCookies),
    };

    await mkdir(dirname(sessionFilePath), { recursive: true });
    const tempFilePath = getSessionTempFilePath(sessionFilePath);
    await writeFile(tempFilePath, `${JSON.stringify(session, null, 2)}\n`, "utf8");
    await rename(tempFilePath, sessionFilePath);
    return session;
  };

  const finalizeCaptureSuccess = async (partition: string): Promise<void> => {
    sessionCache = await saveCredentialSnapshot(partition, { includeSupplementalCookies: true });
    lastError = null;
  };

  return {
    async getState() {
      return currentState();
    },
    async getDiagnostics() {
      return currentDiagnostics();
    },
    async startCapture() {
      if (captureWindow) {
        return currentState();
      }

      lastError = null;
      capturePhase = "preparing";
      captureStartedAtMs = now();
      const partition = stableProfilePartition;
      capturePartition = partition;

      try {
        captureWindow = await options.createCaptureWindow({
          site: options.site,
          partition,
          onClosed: () => {
            captureWindow = null;
            capturePartition = null;
            capturePhase = "idle";
            captureStartedAtMs = null;
            lastError = null;
          },
        });
        capturePhase = "awaiting_confirmation";
        options.log?.("Started site session capture", {
          siteId: options.site.id,
          windowId: captureWindow.id,
          partition,
        });
        return currentState();
      } catch (error) {
        closeCaptureWindow();
        capturePartition = null;
        lastError = summarizeError(error);
        return currentState();
      }
    },
    async confirmCapture() {
      if (!captureWindow || capturePhase !== "awaiting_confirmation" || !capturePartition) {
        return currentState();
      }

      const partition = capturePartition;
      try {
        await finalizeCaptureSuccess(partition);
      } catch (error) {
        lastError = summarizeError(error);
      } finally {
        closeCaptureWindow();
        capturePartition = null;
      }
      return currentState();
    },
    async cancelCapture() {
      closeCaptureWindow();
      capturePartition = null;
      lastError = null;
      return currentState();
    },
    async refreshCredentials() {
      if (capturePhase !== "idle") {
        return currentState();
      }

      try {
        sessionCache = await saveCredentialSnapshot(stableProfilePartition, { includeSupplementalCookies: false });
        lastError = null;
      } catch (error) {
        lastError = summarizeError(error);
      }
      return currentState();
    },
    async clearSession() {
      sessionCache = null;
      lastError = null;
      await rm(sessionFilePath, { force: true }).catch(() => {});
      await options.destroyPartition?.(stableProfilePartition).catch(() => undefined);
      return currentState();
    },
    async shutdown() {
      closeCaptureWindow();
    },
    getDownloadCookies() {
      ensureSessionCacheLoaded();
      return normalizeCookieValue(sessionCache?.cookiesNetscape) ?? null;
    },
  };
};
