import { existsSync, readFileSync } from "node:fs";
import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type {
  SiteSessionDiagnostics,
  SiteSessionState,
  SiteSessionSyncSource,
} from "../src/types/siteSession.js";
import {
  evaluateSiteSessionPolicy,
} from "./siteSessionPolicy.mjs";

type StoredSiteSession = {
  capturedAtMs: number;
  cookies: Record<string, string>;
  cookieHeader: string;
  cookiesNetscape: string;
  source?: SiteSessionSyncSource | null;
};

export type SiteSessionDefinition = {
  id: string;
  displayName: string;
  cookieDomains: string[];
  requiredCookieKeys?: string[];
  loginCookieKeys?: string[];
};

type SiteSessionManagerOptions = {
  site: SiteSessionDefinition;
  getUserDataDir(): string;
  now?(): number;
};

export type ImportedSiteSessionCookie = {
  domain?: string;
  expirationDate?: number;
  httpOnly?: boolean;
  name?: string;
  path?: string;
  secure?: boolean;
  value?: string;
};

export type ImportSiteSessionSnapshotOptions = {
  cookies: ImportedSiteSessionCookie[];
  source?: Partial<SiteSessionSyncSource> | null;
};

export type SiteSessionManager = {
  getState(): Promise<SiteSessionState>;
  getDiagnostics(): Promise<SiteSessionDiagnostics>;
  importSnapshot(options: ImportSiteSessionSnapshotOptions): Promise<SiteSessionState>;
  clearSession(): Promise<SiteSessionState>;
  shutdown(): Promise<void>;
  getDownloadCookies(): string | null;
};

const defaultNow = (): number => Date.now();

const normalizeCookieValue = (value: unknown): string | null => {
  if (typeof value !== "string") {
    return null;
  }
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
};

const sanitizeCookieRecord = (
  value: unknown,
): Record<string, string> => {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }

  const entries = Object.entries(value as Record<string, unknown>)
    .map(([key, raw]) => [key.trim(), normalizeCookieValue(raw)] as const)
    .filter((entry): entry is readonly [string, string] => entry[0].length > 0 && entry[1] !== null);

  return Object.fromEntries(entries);
};

const buildCookieHeader = (
  cookies: Record<string, string>,
): string => Object.entries(cookies)
  .map(([name, value]) => `${name}=${value}`)
  .join("; ");

const normalizeCookieDomain = (domain: string): string => domain.trim().replace(/^\./, "").toLowerCase();

const domainMatches = (cookieDomain: string, allowedDomain: string): boolean => {
  const normalizedCookieDomain = normalizeCookieDomain(cookieDomain);
  const normalizedAllowedDomain = normalizeCookieDomain(allowedDomain);
  return normalizedCookieDomain === normalizedAllowedDomain
    || normalizedCookieDomain.endsWith(`.${normalizedAllowedDomain}`);
};

const isCookieForSite = (
  domain: string | null,
  allowedDomains: string[],
): boolean => {
  const normalizedDomain = normalizeCookieValue(domain);
  if (!normalizedDomain) {
    return false;
  }
  return allowedDomains.some((allowedDomain) => domainMatches(normalizedDomain, allowedDomain));
};

const normalizeSiteCookies = (
  rawCookies: ImportedSiteSessionCookie[],
  allowedDomains: string[],
): Array<{
  domain: string;
  expirationDate?: number;
  name: string;
  path?: string;
  secure?: boolean;
  value: string;
}> => rawCookies
  .map((cookie) => ({
    domain: normalizeCookieValue(cookie.domain),
    expirationDate: cookie.expirationDate,
    name: normalizeCookieValue(cookie.name),
    path: normalizeCookieValue(cookie.path) ?? "/",
    secure: cookie.secure === true,
    value: typeof cookie.value === "string" ? cookie.value : "",
  }))
  .filter((cookie) => Boolean(cookie.domain && cookie.name))
  .filter((cookie) => isCookieForSite(cookie.domain, allowedDomains))
  .map((cookie) => ({
    domain: cookie.domain as string,
    expirationDate: cookie.expirationDate,
    name: cookie.name as string,
    path: cookie.path,
    secure: cookie.secure,
    value: cookie.value,
  }));

const buildNetscapeCookies = (
  cookies: Array<{
    domain: string;
    expirationDate?: number;
    name: string;
    path?: string;
    secure?: boolean;
    value: string;
  }>,
): string => {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# This file was generated by Ameow",
    "",
  ];

  const sortedCookies = [...cookies].sort((left, right) => (
    `${left.domain}\t${left.name}`.localeCompare(`${right.domain}\t${right.name}`)
  ));

  for (const cookie of sortedCookies) {
    const domain = cookie.domain.startsWith(".") ? cookie.domain : `.${cookie.domain}`;
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const expires = Number.isFinite(cookie.expirationDate) && Number(cookie.expirationDate) > 0
      ? String(Math.floor(Number(cookie.expirationDate)))
      : "0";
    lines.push([
      domain,
      includeSubdomains,
      cookie.path?.trim() || "/",
      cookie.secure ? "TRUE" : "FALSE",
      expires,
      cookie.name,
      cookie.value,
    ].join("\t"));
  }

  return `${lines.join("\n")}\n`;
};

const getSessionFilePath = (userDataDir: string, siteId: string): string => (
  join(userDataDir, "site-sessions", `${siteId}.json`)
);

const normalizeSyncSource = (
  value: Partial<SiteSessionSyncSource> | null | undefined,
): SiteSessionSyncSource | null => {
  if (!value || typeof value !== "object") {
    return null;
  }
  const browser = normalizeCookieValue(value.browser);
  const profileLabel = normalizeCookieValue(value.profileLabel);
  const extensionId = normalizeCookieValue(value.extensionId);
  if (!browser && !profileLabel && !extensionId) {
    return null;
  }
  return {
    browser,
    profileLabel,
    extensionId,
  };
};

const getSessionTempFilePath = (sessionFilePath: string): string => (
  `${sessionFilePath}.tmp`
);

const summarizeError = (error: unknown): string => (
  error instanceof Error && error.message ? error.message : String(error ?? "unknown error")
);

const loadStoredSiteSessionSync = (
  sessionFilePath: string,
): StoredSiteSession | null => {
  if (!existsSync(sessionFilePath)) {
    return null;
  }

  try {
    const raw = readFileSync(sessionFilePath, "utf8");
    const parsed = JSON.parse(raw) as unknown;
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return null;
    }

    const record = parsed as Record<string, unknown>;
    const cookies = sanitizeCookieRecord(record.cookies);
    const cookiesNetscape = normalizeCookieValue(record.cookiesNetscape);
    if (Object.keys(cookies).length === 0 || !cookiesNetscape) {
      return null;
    }

    return {
      capturedAtMs: Number(record.capturedAtMs) || 0,
      cookies,
      cookieHeader: normalizeCookieValue(record.cookieHeader) ?? buildCookieHeader(cookies),
      cookiesNetscape,
      source: normalizeSyncSource(record.source as Partial<SiteSessionSyncSource> | null | undefined),
    };
  } catch {
    return null;
  }
};

export const createSiteSessionManager = (
  options: SiteSessionManagerOptions,
): SiteSessionManager => {
  const now = options.now ?? defaultNow;
  const userDataDir = options.getUserDataDir();
  const sessionFilePath = getSessionFilePath(userDataDir, options.site.id);
  const requiredCookieKeys = options.site.requiredCookieKeys ?? [];
  const loginCookieKeys = options.site.loginCookieKeys ?? [];
  let sessionCache: StoredSiteSession | null | undefined;
  let lastError: string | null = null;

  const ensureSessionCacheLoaded = (): void => {
    if (sessionCache !== undefined) {
      return;
    }
    sessionCache = loadStoredSiteSessionSync(sessionFilePath);
  };

  const currentState = (): SiteSessionState => {
    ensureSessionCacheLoaded();
    const cookies = sessionCache?.cookies ?? {};
    const policy = evaluateSiteSessionPolicy({
      cookies,
      requiredKeys: requiredCookieKeys,
      loginKeys: loginCookieKeys,
    });
    const cookieCount = Object.keys(cookies).length;

    return {
      siteId: options.site.id,
      availability: policy.availability,
      updatedAtMs: sessionCache?.capturedAtMs ?? null,
      cookieCount,
      requiredKeys: [...requiredCookieKeys],
      missingRequiredKeys: policy.missingRequiredKeys,
      lastError,
      sessionFilePath: existsSync(sessionFilePath) ? sessionFilePath : null,
      lastSyncSource: sessionCache?.source ?? null,
    };
  };

  const currentDiagnostics = (): SiteSessionDiagnostics => {
    const state = currentState();
    const policy = evaluateSiteSessionPolicy({
      cookies: sessionCache?.cookies ?? {},
      requiredKeys: requiredCookieKeys,
      loginKeys: loginCookieKeys,
    });

    return {
      siteId: options.site.id,
      snapshotAvailability: state.availability,
      snapshotUpdatedAtMs: state.updatedAtMs,
      snapshotCookieCount: state.cookieCount,
      missingRequiredKeys: state.missingRequiredKeys,
      lastError: state.lastError,
      policy,
    };
  };

  const saveCredentialSnapshotFromSiteCookies = async (
    options_: {
      siteCookies: Array<{
        domain: string;
        expirationDate?: number;
        name: string;
        path?: string;
        secure?: boolean;
        value: string;
      }>;
      emptyErrorMessage: string;
      source: SiteSessionSyncSource | null;
    },
  ): Promise<StoredSiteSession> => {
    const primaryCookies = sanitizeCookieRecord(Object.fromEntries(
      options_.siteCookies.map((cookie) => [cookie.name, cookie.value]),
    ));
    const cookies = primaryCookies;
    if (Object.keys(cookies).length === 0) {
      throw new Error(options_.emptyErrorMessage);
    }

    const session: StoredSiteSession = {
      capturedAtMs: now(),
      cookies,
      cookieHeader: buildCookieHeader(cookies),
      cookiesNetscape: buildNetscapeCookies(options_.siteCookies),
      source: options_.source,
    };

    await mkdir(dirname(sessionFilePath), { recursive: true });
    const tempFilePath = getSessionTempFilePath(sessionFilePath);
    await writeFile(tempFilePath, `${JSON.stringify(session, null, 2)}\n`, "utf8");
    await rename(tempFilePath, sessionFilePath);
    return session;
  };

  const importCredentialSnapshot = async (
    importOptions: ImportSiteSessionSnapshotOptions,
  ): Promise<void> => {
    const siteCookies = normalizeSiteCookies(importOptions.cookies, options.site.cookieDomains);
    sessionCache = await saveCredentialSnapshotFromSiteCookies({
      siteCookies,
      emptyErrorMessage: `${options.site.displayName} browser sync finished without saving any cookies.`,
      source: normalizeSyncSource(importOptions.source),
    });
    lastError = null;
  };

  return {
    async getState() {
      return currentState();
    },
    async getDiagnostics() {
      return currentDiagnostics();
    },
    async importSnapshot(importOptions) {
      try {
        await importCredentialSnapshot(importOptions);
      } catch (error) {
        lastError = summarizeError(error);
      }
      return currentState();
    },
    async clearSession() {
      sessionCache = null;
      lastError = null;
      await rm(sessionFilePath, { force: true }).catch(() => {});
      return currentState();
    },
    async shutdown() {
      // Snapshot-only manager has no active window or browser profile to close.
    },
    getDownloadCookies() {
      ensureSessionCacheLoaded();
      return normalizeCookieValue(sessionCache?.cookiesNetscape) ?? null;
    },
  };
};
